l_english:
 peasant_call_to_arms_config_events.0.t: "Call to Arms Configuration"
 peasant_call_to_arms_config_events.0.d: "Here you can configure the behavior of the <BUTTON_NAME> button."
 peasant_call_to_arms_config_events.0_strategy_config: "Configure Call to Arms Strategy"
 peasant_call_to_arms_strongest_military_strategy_active_tt: "Current Strategy: §YPrioritize Strongest Militaries§!"
 peasant_call_to_arms_closest_to_target_strategy_active_tt: "Current Strategy: §YPrioritize Proximity to Target§!"
 peasant_call_to_arms_config_events.0_commune_config: "Configure Which Communes to Summon"
 peasant_call_to_arms_config_events.0_zeal_budget_config: "Configure Peasant Zeal Budget"
 peasant_call_to_arms_config_events.1.t: "Configure Call to Arms Strategy"
 peasant_call_to_arms_config_events.1.d: "Select the priority order for summoning communes. The §Ghighlighted§! option indicates the active strategy."
 peasant_call_to_arms_config_events.1_strongest_military: "Prioritize Strongest Militaries"
 peasant_call_to_arms_config_events.1_closest_to_target_strategy: "Prioritize Proximity to Target"
 peasant_call_to_arms_config_events.3.t: "Configure Peasant Zeal Budget"
 peasant_call_to_arms_config_events.3.d: "Set the maximum amount of Peasant Zeal to spend each time you call all subjects to arms. §GHighlighted§! options indicate the current budget."
 peasant_call_to_arms_zeal_budget: "Peasant Zeal Budget"
 current_zeal_budget_tt: "Current Peasant Zeal Budget: §Y[Root.peasant_call_to_arms_zeal_budget.GetValue]§!"
 peasant_call_to_arms_config_events.3_set_to_100: "100"
 peasant_call_to_arms_config_events.3_set_to_90: "90"
 peasant_call_to_arms_config_events.3_set_to_80: "80"
 peasant_call_to_arms_config_events.3_set_to_70: "70"
 peasant_call_to_arms_config_events.3_set_to_60: "60"
 peasant_call_to_arms_config_events.3_set_to_50: "50"
 peasant_call_to_arms_config_events.3_set_to_40: "40"
 peasant_call_to_arms_config_events.3_set_to_30: "30"
 peasant_call_to_arms_config_events.3_set_to_20: "20"
 peasant_call_to_arms_config_events.3_set_to_10: "10"
 peasant_call_to_arms_config_events.5.t: "Configure Which Communes to Summon"
 peasant_call_to_arms_config_events.5.d: "Toggle the subject types included in the call to arms. §GHighlighted§! types will be summoned."
 peasant_call_to_arms_config_events.5_allied_communes: "£allied_commune£ Allied Communes £allied_commune£"
 peasant_call_to_arms_config_events.5_sister_communes: "£sister_commune£ Sister Communes £sister_commune£"
 peasant_call_to_arms_config_events.5_integrated_communes: "£integrated_commune£ Integrated Communes £integrated_commune£"
 commune_status_tt: "Status for each commune subject type:"
 cta_allied_communes_yes_tt: "£allied_commune£ Allied Communes £allied_commune£: §GEnabled§!"
 cta_allied_communes_no_tt: "£allied_commune£ Allied Communes £allied_commune£: §RDisabled§!"
 cta_sister_communes_yes_tt: "£sister_commune£ Sister Communes £sister_commune£: §GEnabled§!"
 cta_sister_communes_no_tt: "£sister_commune£ Sister Communes £sister_commune£: §RDisabled§!"
 cta_integrated_communes_yes_tt: "£integrated_commune£ Integrated Communes £integrated_commune£: §GEnabled§!"
 cta_integrated_communes_no_tt: "£integrated_commune£ Integrated Communes £integrated_commune£: §RDisabled§!"